services:
  - type: web
    name: smart-cv-generator
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GOOGLE_GENERATIVE_AI_API_KEY
        value: AIzaSyCeTqI8bhTGtsYrpG5jzptvOGzNbN6rjPs
